version: '3.4'
services:
  fastapi-vscode-debug-setup:
    image: fastapi-vscode-debug-setup
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    command: ["sh", "-c", "pip install debugpy -t /tmp && python -Xfrozen_modules=off /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - PIP_ROOT_USER_ACTION=ignore
    ports:
      - 8000:8000
      - 5678:5678