version: '3.4'
services:

  fastapi:
    image: fastapi-vscode
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src/bank_of_kukelia:/app
    command: ["sh", "-c", "python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
    environment:
      - APP_MESSAGE=Hello debugger
    ports:
      - 8000:8000

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    ports:
      - 5432:5432
    #command: COPY ddl.sql /docker-entrypoint-initdb.d/ddl.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=tomas@gmail.com
      - PGADMIN_DEFAULT_PASSWORD="123"
    ports:
      - "8080:80"
    depends_on:
      - postgres